export const INIT_MENU_ITEMS = 'INIT_MENU_ITEMS';
export const ACTIVATE_MENU_ITEM = 'ACTIVATE_MENU_ITEM';
export const INIT_MENU_FOOD = 'INIT_MENU_FOOD';
export const INIT_MENU_DRINKS = 'INIT_MENU_DRINKS';
export const START_INIT_STORIES = 'START_INIT_STORIES';
export const ADD_STORIES_BY_MONTH = 'ADD_STORIES_BY_MONTH';
